autoSwitchLanguage = false
checkModPackTranslationUpdate = true
autoDownloadVMTranslationPack = true
autoInstallVMTranslationPack = false
displayTips = true
playerNameCheck = true
switchLanguage = "zh_cn"
modPackTranslationUpdateCheckUrl = "https://vmct-cn.top/modpacks/dawn/update.txt"
modPackTranslationUrl = "https://vmct-cn.top/modpacks/dawn/"
tipsUrl = "https://vmct-cn.top/tips.txt"
modPackTranslationVersion = "1.0"
tipsMinutes = 20
translationPackName = "VM汉化组模组汉化包1.18"
translationPackUrl = "https://cdn.modrinth.com/data/IDWIdXwS/versions/xCpjJgHS/"
nameUrl = "https://vmct-cn.top/name.json"
